modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "RPL-1.0"

[[mods]]
modId = "caesar"
version = "${version}"
displayName = "Caesar"
authors = "Redstoneguy129"
description = '''
Minecraft Civilizations!
'''
#logoFile = ""

[[dependencies.caesar]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caesar]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caesar]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "caesar.mixins.json"
